train_data_path: /home/majd/screws_classification/screws_set/train 
test_data_path: /home/majd/screws_classification/screws_set/test
pretrained_weights_path: /home/majd/screws_classification/weights

target_image_size: [90, 335]
label_map: ['1', '2']

# training:
val_ratio: 0.2
train_epochs: 3000
save_weights_dir: /home/majd/screws_classification/weights
evaluate_after_training: True

# data generators configs:
train_generator_config: 
        target_image_size: [90, 335]
        batch_size: 32
        resize_fill_mode: 'nearest'
        random_horizontal_flip: 0.5
        random_vertical_flip: 0.5
        random_shift_prob: 0.3
        horizontal_shift_amount: 0.05
        vertical_shift_amount: 0.05
        random_zoom_prob: 1
        zoom_range: [0.95, 1.05]
        random_brightness_shift: True
        brightness_shift_std: 0.15
        fill_mode: 'nearest'

val_generator_config: 
        target_image_size: [90, 335]
        batch_size: 32
        resize_fill_mode: 'nearest'
        
test_generator_config: 
        target_image_size: [90, 335]
        batch_size: 3
        resize_fill_mode: 'nearest'

# inferencing:
classification_threshold: 0.5